Repository Vanessa082/in-touch, pull requests merged in 2024-11, with the labels that each got.

#4 [Feature] Set Up ShadCN UI with Core Folder Structure
  web/components.json
  web/package.json
  web/pnpm-lock.yaml
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/core/components/ui/dropdown-menu.tsx
  web/src/core/fonts/GeistMonoVF.woff
  web/src/core/fonts/GeistVF.woff
  web/src/core/lib/utils.ts
  web/tailwind.config.ts
Labels: enhancement, good first issue, Important

#5 created empty routes for chats, chat[id], and feed
  CONTRIBUTORS
  README.md
  web/src/app/chats/[id]/page.tsx
  web/src/app/chats/page.tsx
  web/src/app/feed/page.tsx
Labels: good first issue

#7 [Feature] Add our custom tailwind colors
  web/tailwind.config.ts
Labels: enhancement, good first issue

#8 added prettierrc, prettierignore,configured the package.json to have …
  web/.eslintrc.json
  web/.prettierignore
  web/.prettierrc
  web/package.json
  web/pnpm-lock.yaml
  web/src/app/chats/[id]/page.tsx
  web/src/app/chats/page.tsx
  web/src/app/feed/page.tsx
  web/src/app/page.tsx
  web/src/core/components/ui/dropdown-menu.tsx
  web/src/core/lib/utils.ts
Labels: enhancement, good first issue, Important

#17 added meta data to the layaout and images
  web/intouch.png
  web/src/app/favicon.ico
  web/src/app/icon.png
  web/src/app/layout.tsx
  web/src/app/opengraph-image.png
  web/src/app/twitter-image.png
Labels: enhancement, good first issue, Important

#21 Feat/landing hero section
  web/package.json
  web/pnpm-lock.yaml
  web/public/home/avatars.svg
  web/public/home/banner-img.svg
  web/public/logo-dark.svg
  web/public/logo-light.svg
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/app/page.tsx
  web/src/core/components/atoms/index.ts
  web/src/core/components/atoms/main-tag.tsx
  web/src/core/components/atoms/text-logo.tsx
  web/src/core/components/home-page/footer.tsx
  web/src/core/components/home-page/header.tsx
  web/src/core/components/home-page/hero-section.tsx
  web/src/core/components/home-page/index.ts
  web/src/core/components/ui/button.tsx
  web/tailwind.config.ts
  web/tsconfig.json
Labels: good first issue, Important

#23 [Feature] Intergrate Clerk auth to app
  README.md
  web/.env.example
  web/.gitignore
  web/README.md
  web/package.json
  web/pnpm-lock.yaml
  web/src/app/(auth)/sign-in/[[...sign-in]]/page.tsx
  web/src/app/(auth)/sign-up/[[...sign-up]]/page.tsx
  web/src/app/feed/page.tsx
  web/src/app/layout.tsx
  web/src/app/profile/page.tsx
  web/src/core/components/atoms/text-logo.tsx
  web/src/core/components/home-page/footer.tsx
  web/src/core/components/home-page/header.tsx
  web/src/core/components/home-page/hero-section.tsx
  web/src/middleware.ts
Labels: enhancement, Important

#22 bootstrap nest api
  api/.eslintrc.js
  api/.gitignore
  api/.prettierrc
  api/README.md
  api/nest-cli.json
  api/package.json
  api/pnpm-lock.yaml
  api/src/app.controller.spec.ts
  api/src/app.controller.ts
  api/src/app.module.ts
  api/src/app.service.ts
  api/src/main.ts
  api/test/app.e2e-spec.ts
  api/test/jest-e2e.json
  api/tsconfig.build.json
  api/tsconfig.json
Labels: enhancement, good first issue, Important

#29 [Feature] Build health endpoint
  api/.eslintrc.js
  api/.prettierrc
  api/nest-cli.json
  api/src/app.controller.spec.ts
  api/src/app.controller.ts
  api/src/app.module.ts
  api/src/app.service.ts
  api/src/interfaces/api-res.ts
  api/src/main.ts
  api/src/modules/app/app.controller.spec.ts
  api/src/modules/app/app.controller.ts
  api/src/modules/app/app.module.ts
  api/src/modules/app/app.service.ts
  api/test/app.e2e-spec.ts
  api/tsconfig.json
Labels: good first issue, api

#32 [Feature] Add our splash screens (loading.tsx)
  web/package.json
  web/pnpm-lock.yaml
  web/src/core/components/home-page/footer.tsx
  web/src/core/components/loading/loading.tsx
Labels: documentation, enhancement, good first issue

#33 [Feature] `SideBar` component
  web/package.json
  web/pnpm-lock.yaml
  web/src/app/(with-side-nav)/chats/[id]/page.ts
  web/src/app/(with-side-nav)/chats/page.ts
  web/src/app/(with-side-nav)/feed/page.ts
  web/src/app/(with-side-nav)/layout.tsx
  web/src/app/(with-side-nav)/profile/page.tsx
  web/src/app/chats/[id]/page.ts
  web/src/app/chats/page.ts
  web/src/app/feed/page.ts
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/core/components/atoms/text-logo.tsx
  web/src/core/components/home-page/header.tsx
  web/src/core/components/molecules/loading/loading.tsx
  web/src/core/components/molecules/side-bar/side-bar.tsx
  web/src/core/components/ui/collapsible.tsx
  web/src/core/components/ui/input.tsx
  web/src/core/components/ui/separator.tsx
  web/src/core/components/ui/sheet.tsx
  web/src/core/components/ui/sidebar.tsx
  web/src/core/components/ui/skeleton.tsx
  web/src/core/components/ui/theme-toggle.tsx
  web/src/core/components/ui/tooltip.tsx
  web/src/core/features/pages/chats/chat-page/chat-page.tsx
  web/src/core/features/pages/chats/chats-page/chats-page.tsx
  web/src/core/features/pages/chats/index.ts
  web/src/core/features/pages/feed-page/feed-page.tsx
  web/src/core/features/pages/index.ts
  web/src/core/hooks/use-mobile.tsx
  web/src/core/pages/chats/chat-page/chat-page.tsx
  web/src/core/pages/chats/chats-page/chats-page.tsx
  web/src/core/pages/feed-page/index.ts
  web/tailwind.config.ts
  web/tsconfig.json
Labels: enhancement

#37 [Fix] Fixed not-found page and fully moved the tailwind css class names
  .gitignore
  web/intouch.png
  web/src/app/(with-side-nav)/chats/layout.ts
  web/src/app/(with-side-nav)/layout.tsx
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/app/not-found.tsx
  web/src/core/components/atoms/text-logo.tsx
  web/src/core/components/home-page/header.tsx
  web/src/core/components/home-page/hero-section.tsx
  web/src/core/components/molecules/loading/loading.tsx
  web/src/core/components/molecules/side-bar/side-bar.tsx
  web/src/core/components/ui/collapsible.tsx
  web/src/core/components/ui/input.tsx
  web/src/core/components/ui/separator.tsx
  web/src/core/components/ui/sheet.tsx
  web/src/core/components/ui/sidebar.tsx
  web/src/core/components/ui/skeleton.tsx
  web/src/core/components/ui/theme-toggle.tsx
  web/src/core/components/ui/tooltip.tsx
  web/src/core/features/pages/chats/chat-page/chat-page.tsx
  web/src/core/features/pages/chats/chats-layout/chats-layout.tsx
  web/src/core/features/pages/chats/chats-page/chats-page.tsx
  web/src/core/features/pages/chats/index.ts
  web/src/core/hooks/use-mobile.tsx
  web/tailwind.config.ts
Labels: enhancement

#43 [Feature] Added the card component
  web/package.json
  web/pnpm-lock.yaml
  web/src/app/api/_dummy-data/chats.data.ts
  web/src/core/components/ui/avatar.tsx
  web/src/core/features/interfaces/chat.types.ts
  web/src/core/features/pages/chats/chats-layout/chat-list/chat-list.tsx
Labels: enhancement, web
